version: 2.1

description: Use ecs-cli commands by orb

orbs:
  orb-tools: circleci/orb-tools@9.1.0
  cli: circleci/circleci-cli@0.1.8

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate

workflows:
  validate:
    jobs:
      - orb-tools/lint
      - orb-tools/shellcheck
      - validate

