version: 2.1

description: Use ecs-cli commands by orb

orbs:
  ecs-cli:
    jobs:
      init:
        executor: default
        steps:
          - install
    commands:
      install:
        description: install AWS ecs-cli
        steps:
          - run:
              name: install tools
              command: |
                sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
                sudo chmod +x /usr/local/bin/ecs-cli
                ecs-cli --version
      run-task:
        parameters:
          compose-yml:
            type: string
          ecs-params-yml:
            type: string
          cluster:
            type: string
            description: cluster name
          launch-type:
            type: string
            default: FARGATE
          force-update:
            type: boolean
            default: true
        steps:
          - run:
              name:
              command: |
                ecs-cli compose --file << parameters.compose-yml >> \
                --ecs-params << parameters.ecs-params-yml >> \
                --region $AWS_REGION \
                --cluster << parameters.cluster >> \
                up \
                --launch-type << parameters.launch-type >>
    executors:
      default:
        docker:
          - image: cimg/base:2020.01
workflows:
  test:
    jobs:
      - ecs-cli/init