version: 2.1

description: Use ecs-cli commands by orb

orbs:
  ecs-cli:
    jobs:
      init:
        executor: default
        steps:
          - install
          - configure
    commands:
      install:
        description: install AWS ecs-cli
        steps:
          - run:
              name: install tools
              command: |
                sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
                sudo chmod +x /usr/local/bin/ecs-cli
                ecs-cli --version
      configure:
        parameters:
          aws-access-key-id:
            default: AWS_ACCESS_KEY_ID
            description: |
              AWS access key id for IAM role. Set this to the name of
              the environment variable you will use to hold this
              value, i.e. AWS_ACCESS_KEY.
            type: env_var_name
          aws-region:
            default: AWS_DEFAULT_REGION
            description: |
              Env var of AWS region to operate in
              (defaults to AWS_DEFAULT_REGION)
            type: env_var_name
          aws-secret-access-key:
            default: AWS_SECRET_ACCESS_KEY
            description: |
              AWS secret key for IAM role. Set this to the name of
              the environment variable you will use to hold this
              value, i.e. $AWS_SECRET_ACCESS_KEY.
            type: env_var_name
        steps:
          - run:
              name: cofigure
              command: ecs-cli configure --cluster test --region ap-northeast-1
          - run:
              name: configure profile
              command: |
                ecs-cli configure profile --profile-name default \
                --access-key << parameters.aws-access-key-id >> \
                --secret-key << parameters.aws-secret-access-key >>
    executors:
      default:
        docker:
          - image: cimg/base:2020.01
workflows:
  test:
    jobs:
      - ecs-cli/init